apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: phpmyadmin/phpmyadmin:latest
          
          ports:
            - containerPort: 8080
          env:
            - name: PMA_HOST
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: admin01
          volumeMounts:
            - mountPath: /var/www/html/
              name: php-storage
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: pvc-php
