apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: 192.168.49.2:5000/php-webserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "user01"
            - name: MYSQL_PASSWORD
              value: "admin01"
            - name: MYSQL_DATABASE
              value: "base01"
          volumeMounts:
            - mountPath: /var/www/html/
              name: php-storage
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: pvc-php
