apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: IfNotPresent
        env:
        - name: PMA_HOST
          value: "mysql" # Esto debe coincidir con el nombre del servicio de MySQL
        ports:
        - containerPort: 80