apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  create-table.sql: |
    CREATE TABLE form_data (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
